name: Deploy to Firebase Hosting on PR

on:
  workflow_call:

jobs:
  build_and_preview:
    if: "${{ github.event.pull_request.head.repo.full_name == github.repository }}"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "yarn"
      - uses: nrwl/nx-set-shas@v2          
      - run: yarn install
      - run: yarn nx affected --target=build --parallel=3
      - uses: FirebaseExtended/action-hosting-deploy@v0
        id: deploy
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_FRONTEND_7E17F }}"
          projectId: frontend-7e17f
      - name: Discord notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          PR_NAME: ${{ github.head_ref }}
          DEPLOY_URL: ${{ steps.deploy.outputs.details_url }}
        uses: Ilshidur/action-discord@0.3.2
        with:
          args: "✨ PR **{{ PR_NAME }}** created/updated 🚀 Deploy url: {{ DEPLOY_URL }}"
