name: lts Main

on:
  workflow_dispatch:

env:
  NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Checkout [main]
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        name: Setup node
        with:
          node-version: 20
          cache: 'yarn'

      - name: Install jq
        run: |
          sudo apt-get update
          sudo apt-get install jq

      - run: yarn install --frozen-lockfile
        name: Install dependencies

      - name: Build
        env:
          alchemyMain: ${{ secrets.ALCHEMY_MAIN_API_KEY }}
          alchemyFallback: ${{ secrets.ALCHEMY_FALLBACK_API_KEY }}
        run: NX_ALCHEMY_MAIN_API_KEY=$alchemyMain NX_ALCHEMY_FALLBACK_API_KEY=$alchemyFallback yarn nx build lts

      - name: Copy Firebase LTS to Firebase
        run: cp firebase.lts.json firebase.json

      - name: Firebase deploy
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_APPS_LTS }}'
          projectId: apps-lts
          channelId: live

      - name: Discord notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@0.3.2
        with:
          args: '✅ New PROD version of LTS 🚀 Deploy url: https://withdraw.mstable.org'
