name: Publish PR

on:
  pull_request:
    branches:
      - dev
    paths-ignore:
      - '**/*.@(md|mdx)'
      - 'libs/subgraph/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}

jobs:
  main:
    runs-on: ubuntu-latest
    env:
      NX_THE_GRAPH_MV_MAINNET_URL: ${{ secrets.NX_THE_GRAPH_MV_MAINNET_URL }}
      NX_THE_GRAPH_MV_GOERLI_URL: ${{ secrets.NX_THE_GRAPH_MV_GOERLI_URL }}
    steps:
      - uses: actions/checkout@v2
        name: Checkout [main]
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        name: Setup node
        with:
          node-version: 16
          cache: "yarn"

      - run: yarn install --frozen-lockfile
        name: Install dependencies

      - name: Build
        env:          
          infura: ${{ secrets.INFURA_API_KEY }}
        run: NX_INFURA_API_KEY=$infura yarn build

      - uses: FirebaseExtended/action-hosting-deploy@v0
        name: Firebase deploy
        id: deploy
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_FRONTEND_7E17F }}"
          projectId: frontend-7e17f

      - name: Discord notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          PR_NAME: ${{ github.head_ref }}
          DEPLOY_URL: ${{ steps.deploy.outputs.details_url }}
        uses: Ilshidur/action-discord@0.3.2
        with:
          args: "✨ PR **{{ PR_NAME }}** created/updated 🚀 Deploy url: {{ DEPLOY_URL }}"
